let shopItemsData = [
  {
    id: "CpuI",
    name: "ryzen 5 3600",
    price: 460,
    desc: "AMD Ryzen 5 3600 A 6 Core 12 Threads Cpu with Base 3.6gh and Boost 4.2GH ",
    img: "images/53600.png",
  },
  {
    id: "cpuII",
    name: "Ryzen 7 5800x3d",
    price: 1250,
    desc: "AMD Ryzen 7 5800x3d A 8 Core 16 Threads Cpu with Base 3.6gh and Boost 4.5GH.",
    img: "images/75800x3d.png",
  },
  {
    id: "cpuIII",
    name: "Intel core i5 12400f",
    price: 560,
    desc: "Intel core i5 12400f A 6 Core 12 Threads Cpu with Base 4GH and Boost 4.6GH.",
    img: "images/i512400f.png",
  },
  {
    id: "gpuI",
    name: "Rx6600XT",
    price: 2100,
    desc: "GIgabayte Radeon Rx6600X Eagle 8gb GDDR6",
    img: "images/gpu1.png",
  },{
    id: "gpuII",
    name: "RTX 4090",
    price: 10000,
    desc: "Gigabyte Geforce RTX 4090 Gaming OC 24GB.",
    img: "images/gpu2.png",
  },{
    id: "gpuIII",
    name: "RX 7800XT",
    price: 2800,
    desc: "SAPPHIRE PURE RTX Radeon RX7800XT 16GB.",
    img: "images/gpu3.png",
  },{
    id: "mbI",
    name: "B550M",
    price: 560,
    desc: "GIGABYTE B550M AROUS ELITE AM4 MOTHERBORD.",
    img: "images/MB1.png",
  },{
    id: "mbII",
    name: "ASROCK B550M",
    price: 549,
    desc: "ASROCK B550M STEEL LEGEND AM4 MOTHERBORD.",
    img: "images/MB2.png",
  },{
    id: "mbIII",
    name: "ASUS TUF B660M",
    price: 1669,
    desc: "ASUS TUF B660M GAMING D5 LG1700 MOTHERBORD.",
    img: "images/MB3.png",
  },{
    id: "pwrI",
    name: "CORSAIR CX SERIES",
    price: 390,
    desc: "CORSAIR CX SERIES 80PLUS BRONZE NON MODULAR POWER SUPPLAY.",
    img: "images/pwrsply1.png",
  },{
    id: "pwrII",
    name: "COOLER MASTER MWE",
    price: 379,
    desc: "COOLER MASTER MWE BRONZE V2 80PLUS NON MODULAR POWER SUPPLAY.",
    img: "images/pwrsply2.png",
  },{
    id: "pwrIII",
    name: "GIGABYTE 80+ BRONZE ",
    price: 289,
    desc: "GIGABYTE 80 BRONZE 650W 80PLUS NON MODULAR POWER SUPPLAY.",
    img: "images/pwrsply3.png",
  },{
    id: "m1",
    name: "VIEWSONIC VX2479-FHD-PRO ",
    price: 640,
    desc: "VIEWSONIC VX2479-FHD-PRO Monitor",
    img: "images/mntr1.png",
  },{
    id: "m2",
    name: "LG Ultragear 27GQ50F",
    price: 655,
    desc: "LG Ultragear 27GQ50F Monitor",
    img: "images/mntr2.png",
  },{
    id: "m3",
    name: "SAMSUNG ODYSSEY G50A QHD",
    price: 1022,
    desc: "SAMSUNG ODYSSEY G50A QHD Monitor",
    img: "images/mntr3.png",
  },
];
